import type { Metadata } from 'next';
import './globals.css';
import { MiniKitContextProvider } from '../providers/MiniKitProvider';
import { WagmiProvider } from '../providers/WagmiProvider';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || 'MiniKit App',
  description: 'Generated by MiniKit integration',
  other: {
    'fc:frame': JSON.stringify({
      version: 'next',
      imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
      button: {
        title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || 'MiniKit App'}`,
        action: {
          type: 'launch_frame',
          name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || 'MiniKit App',
          url: process.env.NEXT_PUBLIC_URL,
          splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
          splashBackgroundColor: process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
        },
      },
    }),
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <WagmiProvider>
          <MiniKitContextProvider>{children}</MiniKitContextProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}

